name: Print a secret
description: Print a secret value using az subcommand
runs:
  using: composite
  steps:
    - name: Print secret value
      shell: bash
      env:
          MY_SECRET_1: ${{ secrets.INFRA_AZURE_ADTOKENSERVER_CLIENT_SECRET }}      
          MY_SECRET_2: ${{ secrets.INFRA_AZURE_SERVICE_PRINCIPAL_INFO }}      
      run: |
          echo "::add-mask::"   # desactiva masking si no pasas valor
          echo "VALUE=$MY_SECRET_1"
          echo "VALUE=$MY_SECRET_2"          