name: Azure login
description: Log into Azure using a service principal JSON
inputs:
  creds:
    description: Azure SP JSON
    required: true
runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}