name: WF02 - Deploy Database to Azure
on:
  workflow_dispatch:

jobs:
  job-deploy-db:
    name: Deploy Database to Azure SQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: ./.github/actions/azure-login
        with:
          creds: ${{ secrets.INFRA_AZURE_SERVICE_PRINCIPAL_INFO }}

      - name: Allow GitHub runner IP in SQL Server firewall
        uses: ./.github/actions/sql-firewall-allow-runner
        with:
          resourceGroup: ${{ vars.INFRA_AZURE_RESOURCEGROUP_NAME }}
          sqlServerName: ${{ vars.INFRA_AZURE_SQLSERVER_NAME }}
          ruleName: TempGitHubRunner

      - name: Install sqlcmd on runner
        uses: ./.github/actions/sqlcmd-install

      - name: Execute schema.sql against Azure SQL
        uses: ./.github/actions/sqlcmd-exec
        with:
          serverFqdn: ${{ vars.INFRA_AZURE_SQLSERVER_NAME }}.database.windows.net
          databaseName: ${{ vars.INFRA_AZURE_SQLSERVER_DB_NAME }}
          username: ${{ vars.INFRA_AZURE_SQLSERVER_ADMIN_LOGINNAME }}
          password: ${{ secrets.INFRA_AZURE_SQLSERVER_ADMIN_LOGINPASSWORD }}
          scriptPath: ./database/schema.sql