name: WF05 - Deploy AD Token Server to Azure
on:
  workflow_dispatch:

jobs:
  deploy-adtokenserver:
    name: Build, push Docker image to ACR and update Azure Container App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: ./.github/actions/azure-login
        with:
          creds: ${{ secrets.INFRA_AZURE_SERVICE_PRINCIPAL_INFO }}

      - name: Build and Push Docker Image to ACR
        uses: ./.github/actions/acr-build-push
        with:
          acrName: ${{ vars.INFRA_AZURE_ACR_NAME }}
          imageName: ${{ vars.INFRA_ADTOKENSERVER_IMAGE_NAME }}
          imageVersion: ${GITHUB_SHA}
          workingDir: ./ad-token-server
          dockerfile: docker/Dockerfile

      - name: Update Azure Container App with New Image
        uses: ./.github/actions/containerapp-update-image
        with:
          resourceGroup: ${{ vars.INFRA_AZURE_RESOURCEGROUP_NAME }}
          containerAppName: ${{ vars.INFRA_AZURE_CONTAINERAPP_ADTOKENSERVER_NAME }}
          acrName: ${{ vars.INFRA_AZURE_ACR_NAME }}
          imageName: ${{ vars.INFRA_ADTOKENSERVER_IMAGE_NAME }}
          imageVersion: ${GITHUB_SHA}
