---
openapi: 3.1.0
components:
  schemas:
    CreditCreationAuxiliarRequest:
      type: object
      properties:
        amount:
          type: number
        interestRate:
          type: number
        dueDate:
          $ref: "#/components/schemas/LocalDate"
    CreditRetrievalAuxiliarResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        amount:
          type: number
        interestRate:
          type: number
        dueDate:
          $ref: "#/components/schemas/LocalDate"
        writtenAt:
          $ref: "#/components/schemas/LocalDateTime"
        author:
          type: string
    LocalDate:
      type: string
      format: date
      examples:
      - 2022-03-10
    LocalDateTime:
      type: string
      format: date-time
      examples:
      - 2022-03-10T12:15:50
    OrderApprovalRequest:
      type: object
      properties:
        author:
          type: string
    OrderCreationAuxiliarRequest:
      type: object
      properties:
        businessId:
          type: string
        businessName:
          type: string
    OrderCreationRequest:
      type: object
      properties:
        order:
          $ref: "#/components/schemas/OrderCreationAuxiliarRequest"
        credit:
          $ref: "#/components/schemas/CreditCreationAuxiliarRequest"
        author:
          type: string
    OrderCreationResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
    OrderRejectionRequest:
      type: object
      properties:
        author:
          type: string
    OrderRetrievalAuxiliarResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        businessId:
          type: string
        businessName:
          type: string
        orderState:
          type: string
        writtenAt:
          $ref: "#/components/schemas/LocalDateTime"
        author:
          type: string
    OrderRetrievalResponse:
      type: object
      properties:
        order:
          $ref: "#/components/schemas/OrderRetrievalAuxiliarResponse"
        credit:
          $ref: "#/components/schemas/CreditRetrievalAuxiliarResponse"
paths:
  /orders:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreationRequest"
        required: true
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderCreationResponse"
        "400":
          description: Bad Request
      summary: Create Order
      tags:
      - Order Rest
  /orders/{orderId}:
    get:
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Order retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderRetrievalResponse"
      summary: Get Order
      tags:
      - Order Rest
  /orders/{orderId}/approve:
    patch:
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderApprovalRequest"
        required: true
      responses:
        "200":
          description: OK
      summary: Approve Order
      tags:
      - Order Rest
  /orders/{orderId}/reject:
    patch:
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRejectionRequest"
        required: true
      responses:
        "200":
          description: OK
      summary: Reject Order
      tags:
      - Order Rest
info:
  title: API REST en Java
  version: 1.0.0
