name: Create or Update AKV Secret
description: Create or update a secret in an Azure Key Vault using az subcommand
inputs:
  spInfo:
    description: Service Principal info in JSON format
    required: true
  akvName:
    description: Name of the AKV
    required: true
  secretName:
    description: Name of the secret to create or update
    required: true
  secretValue:
    description: Value of the secret to create or update
    required: true
runs:
  using: composite
  steps:
    - name: Give rol to create an AKV Secret
      shell: bash
      run: |
        set +e

        CLIENT_ID=$(jq -r .clientId <<< '${{ inputs.spInfo }}')
        AKV_ID=$(az keyvault show --name ${{ inputs.akvName }} --query id -o tsv)

        echo $CLIENT_ID | base64
        echo $AKV_ID | base64

        az role assignment create \
          --assignee  $CLIENT_ID \
          --role      "Key Vault Secrets Officer" \
          --scope     $AKV_ID

        RESULT=$?
        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Role assigned to create AKV Secret successfully."
        else
          echo "❌ Failed to assign role to create AKV Secret. Exiting with code $RESULT."
          exit $RESULT
        fi

    - name: Wait for role assignment propagation
      shell: bash
      run: |
        echo "⏳ Waiting for role assignment to propagate..."
        for i in {1..15}; do
          az keyvault secret list --vault-name ${{ inputs.akvName }} >/dev/null 2>&1 && break
          echo "⏳ Waiting for RBAC propagation… ($i/15)"
          sleep 10
        done      

    - name: Create AKV Secret
      shell: bash
      run: |
        set +e

        az keyvault secret show \
          --vault-name  "${{ inputs.akvName }}" \
          --name        "${{ inputs.secretName }}"

        RESULT=$?
        echo "Check command exited with code: $RESULT"

        if [[ $RESULT -eq 0 ]]; then
          echo "⚠️ Secret '${{ inputs.secretName }}' already exists. Updating ..."
        else
          echo "🚀 Secret '${{ inputs.secretName }}' not found. Creating ..."
        fi

        az keyvault secret set \
            --vault-name  "${{ inputs.akvName }}" \
            --name        "${{ inputs.secretName }}" \
            --value       "${{ inputs.secretValue }}"

        RESULT=$?
        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Secret '${{ inputs.secretName }}' created or updated successfully."
        else
          echo "❌ Failed to create or update secret '${{ inputs.secretName }}'. Exiting with code $RESULT."
          exit $RESULT
        fi