name: Create or Update AKV Secret
description: Create or update a secret in an Azure Key Vault using az subcommand
inputs:
  akvName:
    description: Name of the AKV
    required: true
  secretName:
    description: Name of the secret to create or update
    required: true
  secretValue:
    description: Value of the secret to create or update
    required: true
runs:
  using: composite
  steps:
    - name: Create AKV Secret
      shell: bash
      run: |
        set +e

        az keyvault secret show \
          --vault-name  "${{ inputs.akvName }}" \
          --name        "${{ inputs.secretName }}"

        RESULT=$?
        echo "Check command exited with code: $RESULT"

        if [[ $RESULT -eq 0 ]]; then
          echo "⚠️ Secret '${{ inputs.secretName }}' already exists. Updating ..."
        else
          echo "🚀 Secret '${{ inputs.secretName }}' not found. Creating ..."
        fi

        az keyvault secret set \
            --vault-name  "${{ inputs.akvName }}" \
            --name        "${{ inputs.secretName }}" \
            --value       "${{ inputs.secretValue }}"

        RESULT=$?
        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Secret '${{ inputs.secretName }}' created or updated successfully."
        else
          echo "❌ Failed to create or update secret '${{ inputs.secretName }}'. Exiting with code $RESULT."
          exit $RESULT
        fi