name: SQL firewall allow runner IP
description: Adds/updates a firewall rule in Azure SQL Server with the current local IP
inputs:
  resourceGroup:
    description: The name of the resource group containing the SQL server
    required: true
  sqlServerName:
    description: The name of the SQL server
    required: true
  ruleName:
    description: The name of the firewall rule to create/update
    required: true
  ip:
    description: The IP address to allow through the firewall
    required: true
runs:
  using: composite
  steps:
    - name: Get local IP and update firewall rule
      shell: bash
      run: |
        RG="${{ inputs.resourceGroup }}"
        SQL_SERVER="${{ inputs.sqlServerName }}"
        RULE="${{ inputs.ruleName }}"
        IP="${{ inputs.ip }}"

        echo "â„¹ï¸ Local public IP: $IP"

        if az sql server firewall-rule show \
            --resource-group "$RG" \
            --server "$SQL_SERVER" \
            --name "$RULE" &>/dev/null; then
          echo "ðŸš€ Rule $RULE exists. Updating to $IP ..."
          az sql server firewall-rule update \
            --resource-group "$RG" \
            --server "$SQL_SERVER" \
            --name "$RULE" \
            --start-ip-address "$IP" \
            --end-ip-address "$IP"
        else
          echo "ðŸš€ Creating rule $RULE for IP $IP ..."
          az sql server firewall-rule create \
            --resource-group "$RG" \
            --server "$SQL_SERVER" \
            --name "$RULE" \
            --start-ip-address "$IP" \
            --end-ip-address "$IP"
        fi