name: Create if not exists
description: Create a resource if not exists using az subcommand
inputs:
  resourceName:
    description: Name of the resource
    required: true
  checkCmd:
    description: Command to check if resource exists
    required: true
  createCmd:
    description: Command to create the resource
    required: true
runs:
  using: composite
  steps:
    - name: Create resource if not exists
      shell: bash
      run: |
       set -euo pipefail

        # DEBUG: imprime el comando que se va a ejecutar (quita el echo en production)
        echo "Checking resource '${{ inputs.resourceName }}' with:"
        echo "  checkCmd: ${{ inputs.checkCmd }}"
              
        if bash -c "${{ inputs.checkCmd }} >/dev/null 2>&1"; then
          echo "тЪая╕П Resource '${{ inputs.resourceName }}' already exists. Skipping creation."
        else
          echo "ЁЯЪА Resource '${{ inputs.resourceName }}' not found. Creating..."
          bash -c "${{ inputs.createCmd }}"
        fi