name: Set CAPP secret from AKV
description: Set Container App secret from Azure Key Vault
inputs:
  resourceGroup:
    description: Name of the Resource Group where the Container App is located
    required: true
  containerAppName:
    description: Name of the Container App to grant access
    required: true
  akvName:
    description: Name of the Azure Key Vault
    required: true
  datasourceUsername:
    description: Login username for Azure SQL
    required: true
  datasourcePassword:
    description: Login password secret value in Azure Key Vault
    required: true
runs:
  using: composite
  steps:
    - name: Set Container App credentials
      shell: bash
      run: |
    - name: Set Container App environment variable for login username
      shell: bash
      run: |
        az containerapp update \
          --name            ${{ inputs.containerAppName }} \
          --resource-group  ${{ inputs.resourceGroup }} \
          --set-env-vars    DATASOURCEUSERNAME=${{ inputs.datasourceUsername }}

        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Container App Env Value 'DATASOURCEUSERNAME' created or updated successfully."
        else
          echo "❌ Failed to create or update Container App Env Value 'DATASOURCEUSERNAME'. Exiting with code $RESULT."
          exit $RESULT
        fi

    - name: Assign a Managed Identity to Container App (if not already assigned)
      shell: bash
      run: |
        az containerapp identity assign \
          --name            ${{ inputs.containerAppName }} \
          --resource-group  ${{ inputs.resourceGroup }} \
          --system-assigned

        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Managed Identity assigned to Container App successfully."
        else
          echo "❌ Failed to assign Managed Identity to Container App. Exiting with code $RESULT."
          exit $RESULT
        fi        

    - name: Grant Container App access to Key Vault
      shell: bash
      run: |
        APP_MI_PRINCIPAL_ID=$(az containerapp show \
                                --name            ${{ inputs.containerAppName }} \
                                --resource-group  ${{ inputs.resourceGroup }} \
                                --query           identity.principalId \
                                --output          tsv)

        az role assignment create \
          --role      "Key Vault Secrets User" \
          --assignee  $APP_MI_PRINCIPAL_ID \
          --scope     $(az keyvault show --name ${{ inputs.akvName }} --query id -o tsv)

        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Key Vault access policy set for Container App successfully."
        else
          echo "❌ Failed to set Key Vault access policy for Container App. Exiting with code $RESULT."
          exit $RESULT
        fi

    - name: Set Container App secret for login password
      shell: bash
      run: |
        az containerapp secret set \
          --name            ${{ inputs.containerAppName }} \
          --resource-group  ${{ inputs.resourceGroup }} \
          --secrets         datasourcepassword=keyvault://${{ inputs.akvName }}/datasourcepassword

        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Container App Secret 'datasourcepassword' created or updated successfully."
        else
          echo "❌ Failed to create or update Container App Secret 'datasourcepassword'. Exiting with code $RESULT."
          exit $RESULT
        fi

    - name: Set Container App environment variable for login password
      shell: bash
      run: |
        az containerapp update \
          --name            ${{ inputs.containerAppName }} \
          --resource-group  ${{ inputs.resourceGroup }} \
          --set-env-vars    DATASOURCEPASSWORD=secretref:datasourcepassword

        if [[ $RESULT -eq 0 ]]; then
          echo "✅ Container App Env Value 'datasourcepassword' created or updated successfully."
        else
          echo "❌ Failed to create or update Container App Env Value 'datasourcepassword'. Exiting with code $RESULT."
          exit $RESULT
        fi
