name: Delete a Container App if it exists
description: Delete a Container App if it exists in Azure
inputs:
  subscriptionId:
    description: Azure Subscription ID
    required: true
  containerAppName:
    description: Name of the resource
    required: true
  resourceGroup:
    description: Name of the Resource Group
    required: true
runs:
  using: composite
  steps:
    - name: Stop container
      shell: bash
      run: |
          set +e

          az containerapp stop \
            --name            ${{ inputs.containerAppName }} \
            --resource-group  ${{ inputs.resourceGroup }} \
            --subscription    ${{ inputs.subscriptionId }}

          RESULT=$?
          if [[ $RESULT -eq 0 ]]; then
            echo "✅ Container app '${{ inputs.containerAppName }}' stopped successfully."
          else
            echo "❌ Failed to stop container app '${{ inputs.containerAppName }}'. Exiting with code $RESULT."
            exit $RESULT
          fi

    - name: Delete container app
      shell: bash
      run: |
          set +e

          az containerapp delete \
            --name            ${{ inputs.containerAppName }} \
            --resource-group  ${{ inputs.resourceGroup }} \
            --subscription    ${{ inputs.subscriptionId }} \
            --yes    

          RESULT=$?
          if [[ $RESULT -eq 0 ]]; then
            echo "✅ Container app '${{ inputs.containerAppName }}' deleted successfully."
          else
            echo "❌ Failed to delete container app '${{ inputs.containerAppName }}'. Exiting with code $RESULT."
            exit $RESULT
          fi
