name: Install sqlcmd (Ubuntu)
description: Installs msodbcsql18, mssql-tools and configures PATH for sqlcmd on Ubuntu runners
runs:
  using: composite
  steps:
    - name: Install sqlcmd and ODBC drivers
      shell: bash
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools unixodbc-dev
        echo "PATH=/opt/mssql-tools/bin:$PATH" >> "$GITHUB_ENV"