name: Deploy Database Schema

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/db/**"

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run schema.sql on Azure SQL
        run: |
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER }} \
                 -d ${{ secrets.AZURE_SQL_DB }} \
                 -U ${{ secrets.AZURE_SQL_USER }} \
                 -P ${{ secrets.AZURE_SQL_PASSWORD }} \
                 -i infra/db/schema.sql
