name: Deploy FrontEnd to Azure

on:
  workflow_dispatch:

jobs:
  job-deploy-frontend:
    runs-on: ubuntu-latest
    env:
      RG: ${{ vars.INFRA_AZURE_RESOURCEGROUP_NAME }}
      ACR: ${{ vars.INFRA_AZURE_ACR_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.INFRA_AZURE_SERVICE_PRINCIPAL_INFO }}

      #############################################
      # Build and push frontend Angular container
      #############################################
      - name: Build Angular frontend Docker image
        run: |
          cd ./frontend/credits
          docker build -t $ACR.azurecr.io/${{ vars.INFRA_FRONTEND_IMAGE_NAME }}:${{ vars.INFRA_FRONTEND_IMAGE_VERSION }} .
          echo "Built frontend image"

      - name: Push frontend to ACR
        run: |
          az acr login --name $ACR
          docker push $ACR.azurecr.io/${{ vars.INFRA_FRONTEND_IMAGE_NAME }}:${{ vars.INFRA_FRONTEND_IMAGE_VERSION }}

      #############################################
      # Deploy Frontend Container App
      #############################################
      - name: Deploy frontend Container App
        run: |
          echo "Updating existing frontend Container App..."
          az containerapp update \
            --name ${{ vars.INFRA_AZURE_CONTAINERAPP_FRONTEND_NAME }} \
            --resource-group $RG \
            --image $ACR.azurecr.io/${{ vars.INFRA_FRONTEND_IMAGE_NAME }}:${{ vars.INFRA_FRONTEND_IMAGE_VERSION }}